spring.application.name=mossy-password
server.port=8082

server.servlet.context-path=/api/v1/passwords/

spring.jpa.hibernate.ddl-auto=update

spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=jdbc:postgresql://${DB_URL}/${DB_NAME}

mossy.jwks.jwks-queue-name=jwks.queue.password
mossy.jwks.jwks-provider-uri=${JWKS_PROVIDER_URI}

mossy.security.allowed-origins=${ALLOWED_ORIGINS}
mossy.security.public-routes-patterns=/ws/vault-communication/**,/vault/statuses,/actuator/health

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

mossy.password.statistics.topic=${KAFKA_TOPIC_PASSWORD_STATISTIC:password.statistic}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.host=${REDIS_HOST}
