spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.jpa.hibernate.ddl-auto=create-drop

mossy.dev.api-key=${API_KEY}
mossy.dev.vault-id=${VAULT_ID}
mossy.dev.vault-name=${VAULT_NAME}
mossy.dev.owner-id=${OWNER_ID}