spring.application.name=mossy-device-trust
server.port=8085
server.servlet.context-path=/api/v1/device-trust

mossy.security.public-routes-patterns=/device,/nonce

spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.host=${REDIS_HOST}