package pl.dayfit.mossyauth.configuration

import org.springframework.boot.context.properties.EnableConfigurationProperties
import org.springframework.context.annotation.Configuration
import pl.dayfit.mossyauth.configuration.properties.CookiesConfigurationProperties

@Configuration
@EnableConfigurationProperties(CookiesConfigurationProperties::class)
class CookieConfiguration