spring.application.name=mossy-statistics
server.port=8085
server.servlet.context-path=/api/v1/statistics

spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=jdbc:postgresql://${DB_URL}/${DB_NAME}
spring.jpa.hibernate.ddl-auto=update

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.username=${RABBITMQ_USER}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=mossy-statistics-consumer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=pl.dayfit.mossystatistics.messaging.dto.PasswordStatisticEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=pl.dayfit.mossystatistics.messaging.dto

mossy.password.base-url=${MOSSY_PASSWORD_BASE_URL:http://localhost:8082/api/v1}

mossy.kafka.topics.password-statistic.name=${KAFKA_TOPIC_PASSWORD_STATISTIC:password.statistic}
mossy.kafka.topics.password-statistic.partitions=${KAFKA_TOPIC_PASSWORD_STATISTIC_PARTITIONS:3}
mossy.kafka.topics.password-statistic.replicas=${KAFKA_TOPIC_PASSWORD_STATISTIC_REPLICAS:1}
mossy.security.public-routes-patterns=/actuator/health

mossy.security.allowed-origins=${ALLOWED_ORIGINS}
mossy.jwks.jwks-provider-uri=${JWKS_PROVIDER_URI}
mossy.jwks.jwks-queue-name=${JWKS_QUEUE_NAME:jwks.queue.statistics}
