spring.application.name=mossy-key-sync
server.port=8081

server.servlet.context-path=/api/v1/
mossy.security.public-routes-patterns=/ws/key-sync/**, /actuator/health
mossy.security.allowed-origins=${ALLOWED_ORIGINS}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWKS_PROVIDER_URI}

spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.host=${REDIS_HOST}
