FROM node:22-alpine AS builder
COPY /mossy-frontend /mossy
WORKDIR /mossy
RUN npm ci && \
     npm run build

FROM node:22-alpine AS runner
RUN npm install -g serve
WORKDIR /mossy
COPY --from=builder /mossy/dist .
EXPOSE 3000
CMD ["serve", "-s", ".", "-l", "3000"]