FROM amazoncorretto:21-alpine3.22-jdk AS build

COPY mossy-jwks/ /mossy/
WORKDIR /mossy

RUN --mount=type=secret,id=gh_name \
    --mount=type=secret,id=github_token \
    sh -c 'echo \
"<settings>" \
"  <servers>" \
"    <server>" \
"      <id>github</id>" \
"      <username>$(cat /run/secrets/gh_name)</username>" \
"      <password>$(cat /run/secrets/github_token)</password>" \
"    </server>" \
"  </servers>" \
"</settings>" > /tmp/settings.xml'

RUN chmod +x ./mvnw && \
    ./mvnw clean package -DskipTests -s /tmp/settings.xml

FROM amazoncorretto:21-al2023-headless
COPY --from=build /mossy/target/mossy-jwks-*.jar /mossy/mossy-jwks.jar
CMD ["java", "-jar", "/mossy/mossy-jwks.jar"]
EXPOSE 8084