FROM amazoncorretto:21-alpine3.22-jdk AS build

COPY mossy-device-trust-shared/ /mossy-device-trust-shared/
COPY mossy-device-trust/ /mossy-device-trust/
WORKDIR /mossy-device-trust

RUN --mount=type=secret,id=gh_name \
    --mount=type=secret,id=github_token \
    sh -c 'echo \
"<settings>" \
"  <servers>" \
"    <server>" \
"      <id>github</id>" \
"      <username>$(cat /run/secrets/gh_name)</username>" \
"      <password>$(cat /run/secrets/github_token)</password>" \
"    </server>" \
"  </servers>" \
"</settings>" > /tmp/settings.xml'

RUN chmod +x ./mvnw && \
    ./mvnw install -DskipTests -f /mossy-device-trust-shared/pom.xml -s /tmp/settings.xml && \
    ./mvnw clean package -DskipTests -s /tmp/settings.xml

FROM amazoncorretto:21-al2023-headless
COPY --from=build /mossy-device-trust/target/mossy-device-trust-*.jar /mossy/mossy-device-trust.jar
CMD ["java", "-jar", "/mossy/mossy-device-trust.jar"]
EXPOSE 8086
