spring.application.name=mossy-mailer
mossy.mailer.resend.api-key=${RESEND_API_KEY}

spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.username=${REDIS_USER:mossy}
spring.data.redis.host=${REDIS_HOST}